const express = require("express");
const app = express();
const port = 3000;
const cors = require("cors");

let houseData = [
  {
    createdAt: "2025-01-23T00:38:25.098Z",
    name: "Luxurious Delhi Duplex",
    avatar:
      "https://plus.unsplash.com/premium_photo-1686090449192-4ab1d00cb735",
    address_city: "New Delhi",
    address_cityname: "Delhi",
    address_building_number: "14",
    address_street_name: "Vasant Vihar Road",
    address_country: "India",
    address_lat: "28.575726",
    address_long: "77.081955",
    address_elevation: 25,
    description:
      "Pristine 3BHK duplex in prime Vasant Vihar location. Features modern interiors, marble flooring, spacious balconies, and panoramic city views. Walking distance to international schools and premium shopping districts. Ideal for executives and expat families seeking luxury living.",
    price: 4500000,
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 2800,
    unlocked: false,
    id: "1",
  },
  {
    createdAt: "2025-01-23T00:45:25.808Z",
    name: "Gurgaon Smart Home",
    avatar:
      "https://plus.unsplash.com/premium_photo-1686090449192-4ab1d00cb735",
    address_city: "Gurgaon",
    address_cityname: "Haryana",
    address_building_number: "39",
    address_street_name: "Golf Course Extension Road",
    address_country: "India",
    address_lat: "28.457523",
    address_long: "77.026354",
    address_elevation: 28,
    description:
      "State-of-the-art 4BHK smart home in Gurgaon's most advanced residential complex. Automated systems, solar panels, IoT-enabled appliances, and high-speed fiber connectivity. Amenities include gym, swimming pool, and 24/7 security. Perfect for tech professionals and modern families.",
    price: 6200000,
    bedrooms: 4,
    bathrooms: 4,
    area_sqft: 3500,
    unlocked: false,
    id: "2",
  },
  {
    createdAt: "2025-01-23T16:10:44.667Z",
    name: "Coastal Paradise Villa",
    avatar:
      "https://plus.unsplash.com/premium_photo-1686090449192-4ab1d00cb735",
    address_city: "Goa",
    address_cityname: "Goa",
    address_building_number: "301",
    address_street_name: "Candolim Beach Road",
    address_country: "India",
    address_lat: "15.299326",
    address_long: "74.123730",
    address_elevation: 12,
    description:
      "Stunning beachfront villa with direct sea access. Features 5 spacious bedrooms, infinity pool, private beach pathway, and contemporary design. Floor-to-ceiling windows offer breathtaking Arabian Sea views. Ideal for luxury vacation home or high-end rental investment.",
    price: 8500000,
    bedrooms: 5,
    bathrooms: 5,
    area_sqft: 4200,
    unlocked: false,
    id: "3",
  },
  {
    createdAt: "2025-01-23T04:13:05.394Z",
    name: "Bangalore Tech Hub Residence",
    avatar:
      "https://plus.unsplash.com/premium_photo-1686090449192-4ab1d00cb735",
    address_city: "Bangalore",
    address_cityname: "Karnataka",
    address_building_number: "604",
    address_street_name: "Indiranagar 100 Feet Road",
    address_country: "India",
    address_lat: "12.972442",
    address_long: "77.580643",
    address_elevation: 920,
    description:
      "Ultra-modern 3BHK apartment in Bangalore's most sought-after tech neighborhood. Open-plan layout, cutting-edge design, home office spaces, and premium amenities. Close to major tech parks, international schools, and premium restaurants. Perfect for tech professionals.",
    price: 5200000,
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 2600,
    unlocked: false,
    id: "4",
  },
  {
    createdAt: "2025-01-23T04:14:56.265Z",
    name: "Kerala Waterfront Retreat",
    avatar:
      "https://plus.unsplash.com/premium_photo-1686090449192-4ab1d00cb735",
    address_city: "Kochi",
    address_cityname: "Kerala",
    address_building_number: "402",
    address_street_name: "Marine Drive",
    address_country: "India",
    address_lat: "9.939248",
    address_long: "76.270523",
    address_elevation: 8,
    description:
      "Luxurious waterfront home overlooking Kochi's serene backwaters. Traditional Kerala architecture blended with modern amenities. Private boat jetty, landscaped gardens, and panoramic water views. Ideal for those seeking tranquil coastal living with contemporary comfort.",
    price: 7800000,
    bedrooms: 4,
    bathrooms: 4,
    area_sqft: 3800,
    unlocked: false,
    id: "5",
  },
  {
    createdAt: "2025-01-23T12:15:37.220Z",
    name: "Mumbai Luxury Penthouse",
    avatar:
      "https://plus.unsplash.com/premium_photo-1686090449192-4ab1d00cb735",
    address_city: "Mumbai",
    address_cityname: "Maharashtra",
    address_building_number: "1008",
    address_street_name: "Worli Sea Face",
    address_country: "India",
    address_lat: "19.075983",
    address_long: "72.877655",
    address_elevation: 15,
    description:
      "Spectacular sea-facing penthouse in Mumbai's most prestigious Worli neighborhood. Expansive living spaces, floor-to-ceiling windows, private terrace, and 360-degree city and sea views. High-end finishes, smart home technology, and exclusive building amenities.",
    price: 9500000,
    bedrooms: 4,
    bathrooms: 5,
    area_sqft: 4500,
    unlocked: false,
    id: "6",
  },
  {
    createdAt: "2025-01-23T08:29:18.044Z",
    name: "Hyderabad Heritage Bungalow",
    avatar:
      "https://plus.unsplash.com/premium_photo-1686090449192-4ab1d00cb735",
    address_city: "Hyderabad",
    address_cityname: "Telangana",
    address_building_number: "705",
    address_street_name: "Banjara Hills Road",
    address_country: "India",
    address_lat: "17.385044",
    address_long: "78.486671",
    address_elevation: 542,
    description:
      "Exquisite colonial-style bungalow in the heart of Banjara Hills. Blend of traditional architecture and modern luxury. Spacious rooms, vintage tile work, landscaped gardens, and private courtyard. Perfect for those who appreciate historic architectural elegance.",
    price: 6800000,
    bedrooms: 4,
    bathrooms: 4,
    area_sqft: 3600,
    unlocked: false,
    id: "7",
  },
  {
    createdAt: "2025-01-23T19:45:22.789Z",
    name: "Pune Hilltop Villa",
    avatar: "https://images.unsplash.com/photo-1483097365279-e8acd3bf9f18",
    address_city: "Pune",
    address_cityname: "Maharashtra",
    address_building_number: "501",
    address_street_name: "Lonavala Road",
    address_country: "India",
    address_lat: "18.520430",
    address_long: "73.856743",
    address_elevation: 560,
    description:
      "Stunning hilltop villa with panoramic mountain views. Modern architecture, infinity pool, expansive outdoor living spaces, and complete privacy. Ideal for weekend retreats or as a permanent residence for those seeking tranquility and natural beauty.",
    price: 7200000,
    bedrooms: 5,
    bathrooms: 4,
    area_sqft: 4000,
    unlocked: false,
    id: "8",
  },
  {
    createdAt: "2025-01-23T20:30:11.234Z",
    name: "Chennai Modern Luxury Apartment",
    avatar: "https://images.unsplash.com/photo-1483097365279-e8acd3bf9f18",
    address_city: "Chennai",
    address_cityname: "Tamil Nadu",
    address_building_number: "204",
    address_street_name: "Boat Club Road",
    address_country: "India",
    address_lat: "13.067439",
    address_long: "80.237617",
    address_elevation: 15,
    description:
      "Exclusive waterfront apartment in Chennai's most prestigious neighborhood. Cutting-edge design, smart home features, private marina access, and panoramic Bay of Bengal views. High-end finishes, state-of-the-art security, and world-class amenities.",
    price: 5600000,
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 2800,
    unlocked: false,
    id: "9",
  },
  {
    createdAt: "2025-01-23T21:15:56.567Z",
    name: "Jaipur Royal Heritage Home",
    avatar: "https://images.unsplash.com/photo-1483097365279-e8acd3bf9f18",
    address_city: "Jaipur",
    address_cityname: "Rajasthan",
    address_building_number: "301",
    address_street_name: "C-Scheme",
    address_country: "India",
    address_lat: "26.912434",
    address_long: "75.787271",
    address_elevation: 386,
    description:
      "Majestic home blending traditional Rajasthani architecture with modern luxury. Intricate marble work, hand-painted ceilings, private courtyard, and landscaped gardens. Located in the cultural heart of Jaipur, offering a unique living experience for those who appreciate historical elegance.",
    price: 7500000,
    bedrooms: 4,
    bathrooms: 4,
    area_sqft: 3900,
    unlocked: false,
    id: "10",
  },
  {
    createdAt: "2025-01-24T02:45:33.210Z",
    name: "Kolkata Riverside Mansion",
    avatar: "https://images.unsplash.com/photo-1483097365279-e8acd3bf9f18",
    address_city: "Kolkata",
    address_cityname: "West Bengal",
    address_building_number: "456",
    address_street_name: "Strand Road",
    address_country: "India",
    address_lat: "22.569674",
    address_long: "88.363895",
    address_elevation: 6,
    description:
      "Magnificent riverside residence with unobstructed Hooghly River views. Colonial-inspired architecture, expansive living spaces, private dock, and meticulously designed interiors. Perfect for those seeking a blend of historic charm and modern comfort in Kolkata's most prestigious location.",
    price: 6900000,
    bedrooms: 5,
    bathrooms: 5,
    area_sqft: 4200,
    unlocked: false,
    id: "11",
  },
  {
    createdAt: "2025-01-24T03:30:22.456Z",
    name: "Ahmedabad Modern Oasis",
    avatar: "https://images.unsplash.com/photo-1483097365279-e8acd3bf9f18",
    address_city: "Ahmedabad",
    address_cityname: "Gujarat",
    address_building_number: "789",
    address_street_name: "Satellite Road",
    address_country: "India",
    address_lat: "23.022505",
    address_long: "72.571362",
    address_elevation: 55,
    description:
      "Contemporary architectural marvel in Ahmedabad's most sought-after neighborhood. Minimalist design, sustainable features, smart home technology, and expansive living spaces. Private terrace, infinity pool, and cutting-edge home automation systems.",
    price: 5800000,
    bedrooms: 4,
    bathrooms: 4,
    area_sqft: 3700,
    unlocked: false,
    id: "12",
  },
  {
    createdAt: "2025-01-24T04:15:11.789Z",
    name: "Chandigarh Architectural Gem",
    avatar: "https://images.unsplash.com/photo-1483097365279-e8acd3bf9f18",
    address_city: "Chandigarh",
    address_cityname: "Punjab",
    address_building_number: "234",
    address_street_name: "Sector 16",
    address_country: "India",
    address_lat: "30.736286",
    address_long: "76.781391",
    address_elevation: 321,
    description:
      "Masterpiece of modernist design in Le Corbusier's planned city. Innovative architectural layout, expansive windows, integrated landscaping, and meticulously preserved original design elements. A rare opportunity for architecture enthusiasts and those appreciating urban planning.",
    price: 6300000,
    bedrooms: 4,
    bathrooms: 3,
    area_sqft: 3500,
    unlocked: false,
    id: "13",
  },
  {
    createdAt: "2025-01-24T05:00:44.321Z",
    name: "Shimla Mountain Retreat",
    avatar: "https://images.unsplash.com/photo-1483097365279-e8acd3bf9f18",
    address_city: "Shimla",
    address_cityname: "Himachal Pradesh",
    address_building_number: "567",
    address_street_name: "Mall Road",
    address_country: "India",
    address_lat: "31.104378",
    address_long: "77.173036",
    address_elevation: 2276,
    description:
      "Luxurious mountain residence with breathtaking Himalayan views. Sophisticated alpine-inspired design, heated floors, panoramic windows, and private forest access. Perfect winter retreat or year-round mountain home for those seeking tranquility and natural beauty.",
    price: 7900000,
    bedrooms: 5,
    bathrooms: 4,
    area_sqft: 4100,
    unlocked: false,
    id: "14",
  },
  {
    createdAt: "2025-01-24T05:45:33.654Z",
    name: "Coorg Coffee Plantation Bungalow",
    avatar: "https://images.unsplash.com/photo-1483097365279-e8acd3bf9f18",
    address_city: "Madikeri",
    address_cityname: "Karnataka",
    address_building_number: "891",
    address_street_name: "Coffee Estate Road",
    address_country: "India",
    address_lat: "12.429498",
    address_long: "75.738586",
    address_elevation: 900,
    description:
      "Exclusive bungalow nestled within a working coffee plantation. Rustic-luxury design, expansive verandas, private coffee garden, and stunning Western Ghats backdrop. Ideal for those seeking a unique lifestyle combining agricultural charm with modern comfort.",
    price: 5500000,
    bedrooms: 4,
    bathrooms: 3,
    area_sqft: 3200,
    unlocked: false,
    id: "15",
  },
  {
    createdAt: "2025-01-24T06:30:22.987Z",
    name: "Udaipur Lake View Palace",
    avatar: "https://images.unsplash.com/photo-1483097365279-e8acd3bf9f18",
    address_city: "Udaipur",
    address_cityname: "Rajasthan",
    address_building_number: "345",
    address_street_name: "Lake Palace Road",
    address_country: "India",
    address_lat: "24.585445",
    address_long: "73.712479",
    address_elevation: 443,
    description:
      "Majestic residence overlooking Lake Pichola, inspired by royal Rajput architecture. Intricate marble work, private lake-facing terrace, traditional courtyard, and modern amenities. A once-in-a-lifetime opportunity to own a piece of Rajasthan's architectural heritage.",
    price: 8200000,
    bedrooms: 5,
    bathrooms: 5,
    area_sqft: 4500,
    unlocked: false,
    id: "16",
  },
  {
    createdAt: "2025-01-24T07:15:11.432Z",
    name: "Kochi Backwater Sanctuary",
    avatar: "https://images.unsplash.com/photo-1483097365279-e8acd3bf9f18",
    address_city: "Kochi",
    address_cityname: "Kerala",
    address_building_number: "678",
    address_street_name: "Marine Drive",
    address_country: "India",
    address_lat: "9.939248",
    address_long: "76.270523",
    address_elevation: 8,
    description:
      "Extraordinary waterfront home with direct backwater access. Contemporary design blending traditional Kerala architectural elements, private boat dock, lush tropical gardens, and uninterrupted water views. A serene escape for those seeking ultimate tranquility.",
    price: 6700000,
    bedrooms: 4,
    bathrooms: 4,
    area_sqft: 3800,
    unlocked: false,
    id: "17",
  },
  {
    createdAt: "2025-01-24T07:15:11.432Z",
    name: "My Home",
    avatar: "https://images.unsplash.com/photo-1483097365279-e8acd3bf9f18",
    address_city: "my",
    address_cityname: "",
    address_building_number: "",
    address_street_name: "",
    address_country: "",
    address_lat: "28.575412",
    address_long: "77.0810892",
    address_elevation: "",
    description: "",
    price: 0,
    bedrooms: 0,
    bathrooms: 0,
    area_sqft: 0,
    unlocked: false,
    id: "18",
  },
  {
    createdAt: "2025-01-24T07:15:11.432Z",
    name: "test home",
    avatar: "https://images.unsplash.com/photo-1483097365279-e8acd3bf9f18",
    address_city: "testing location",
    address_cityname: "111",
    address_building_number: "222",
    address_street_name: "333",
    address_country: "444",
    address_lat: "28.5753342",
    address_long: "77.0815594",
    address_elevation: "555",
    description: "testing description",
    price: 0,
    bedrooms: 0,
    bathrooms: 0,
    area_sqft: 0,
    unlocked: false,
    id: "19",
  },
];

app.use(express.json());
app.use(cors());

app.get("/houses", (req, res) => {
  res.json(houseData);
});

app.get("/houses/:id", (req, res) => {
  const house = houseData.find((h) => h.id === req.params.id);
  if (!house) {
    return res.status(404).json({ message: "House not found" });
  }
  res.json(house);
});

app.put("/house/:id", (req, res) => {
  const house = houseData.find((h) => h.id === req.params.id);
  if (!house) {
    return res.status(404).json({ message: "House not found" });
  }
  house.unlocked = true;
  res.json({ message: "House updated successfully", house });
});

app.listen(port, () => {
  console.log(`Server running on http://localhost:${port}`);
});
